export { default as Footer } from "./Footer"
export { default as Header } from "./Header"
export { default as NotFound } from "./NotFound"
export { default as Pagination } from "./Pagination"
export { default as SpinnerLoading } from "./SpinnerLoading"
